name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build MSI (Windows EXE)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build MSI package
        run: ./gradlew :composeApp:packageReleaseMsi

      - name: Upload MSI installer
        uses: actions/upload-artifact@v4
        with:
          name: ElektronSportInstaller
          path: composeApp/build/compose/binaries/main-release/msi/*.msi
